server:
  port: ":8080"

database:
  host: "db"
  port: "5432"
  user: "postgres"
#  password: "postgres"
  dbname: "urlshortener"

redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0
#
#jwt:
#  secret: "hasdjahsjdashdi13uye9u1hejshdkjashdkjashdaskdhajks"
